# rails g controller likes --no-assets --no-helper --no-controller-specs --no-views-specs --skip-template-engine
# this controller is generated by using above 👆🏻command
class LikesController < ApplicationController
    def create
        question= Question.find params[:question_id] 
        like= Like.new question: question, user: current_user
        if !can?(:like, question)
            flash[:alert]='You can not like your own question'
        elsif like.save
            flash[:notice]='Question liked'
        else
            flash[:alert]=like.errors.full_messages.join(', ')
        end
        redirect_to question_path(question)
    end
    def destroy
        like = current_user.likes.find params[:id]
        if !can?(:destroy, like)
            flash[:alert]= 'You can\'t destroy a liek you don\'t own'
        elsif like.destroy
            flash[:notice]='Question unliked' 
        else
            flash[:alert]='Couldn\'t unlike the question'
        end
        redirect_to question_path(like.question)
    end
end
